praekeltfoundation/ndoh-hub

changes/tasks.py
changes/tests.py
ndoh_hub/utils_tests.py

When you use SMS (Stop):
When you use USSD:
Also does an amazing thing for baby switch that caters for current and migrated pmtct app versions.

Adjust opt-out strategy

---

registrations/admin.py

This currently breaks searching in the django admin.

Fix admin search - to_addr is not a valid field

---

changes/management/commands/jembi_submit_babyloss.py
changes/tasks.py
changes/tests.py

This adds functionality that will send a payload to jembi when a baby loss change is created.
Also, a management command to resubmit any missed changes

Notify jembi of baby loss change

---

registrations/serializers.py
registrations/tasks.py
registrations/tests.py
registrations/views.py

This PR adds the optional field "encdate" to the 3rd party integrations, if it is not included in the payload the old functionality will apply(get_timestamp).
The reason for this change is to make the "encdate" field more accurate when sending historical registrations to the hub.

Support for encdate to 3rd party registrations

---

changes/management/commands/jembi_submit_babyswitch.py
changes/tasks.py
changes/tests.py

This adds functionality that will send a payload to jembi when a baby switch change is created.
Also, a management command to resubmit any missed changes

Notify jembi of baby switch change

---

registrations/tasks.py
registrations/tests.py

The PMTCT registrations does not have any data we can use to identify a patient, so we do a call to the identity store to get the msisdn. We can then send the registration to Jembi.

Adds a call to identity store for msisdn

---

registrations/tasks.py
registrations/tests.py

The dmsisdn field is also a required field on Jembi, so we are also populating it with the msisdn we get from the identity store if we don't have one on the registration.
I tested this payload manually and it worked on their QA system.

Use idenity msisdn for the device msisdn

---

registrations/management/commands/fix_pmtct_registrations.py
registrations/tests.py

Since the migration the new PMTCT registrations have been failing to validate, this is because the `edd` field was not populated.
This commands looks for a related subscription of a different type that is validated to get the `edd` date. It will then resubmit it for validation.

Command to fix unvalidated PMTCT optouts

---

registrations/management/commands/fix_pmtct_registrations.py

The field loop also changed, some registrations have the `edd` field with a null value.

Added support for different fields for postbirth type

---

changes/tasks.py
changes/tests.py
registrations/tasks.py
registrations/tests.py

One of the fields that is being sent to Jembi is `encdate`, this requires the timestamp of when the event happened, because we sometimes send through items late, it is better to use the item create date instead of current timestamp.

Change encdate to create date of item

---

registrations/management/commands/report_pmtct_risks.py
registrations/tests.py

Fix ".get" for 'edd' field, postbirth doesn't have this field.
To use a remote hub the user can include a hub-url and hub-token
User can now group by msisdn, will need to include identity-store-url and identity-store-token

Small fix,changed for remote hub and per msisdn

---

changes/tests.py
changes/urls.py
changes/views.py

Adds an endpoint to optout identities that have failed to receive messages.
The endpoint expects the identity to optout and creates an optout change with the reason of `sms_failure`

Endpoint to create an Optout change when messages have repeatedly failed

---

changes/tasks.py
changes/tests.py

When changing the language of an identity, we should keep the old language somewhere so that we have a record of it.

Add old language to change object when changing identity language

---

ndoh_hub/utils_tests.py
registrations/admin.py
registrations/tasks.py
registrations/tests.py

Currently, there is personal information stored in registrations, so when we "forget" a user in the identity store, wiping the information from there doesn't clear all the information we have on them.
Instead, once we are done with this information, we should make sure it's stored on the identity, in case we need it later, and then we should remove it from the registration object in the database.

Remove personal information from registrations

---

changes/management/commands/jembi_submit_babyloss.py
changes/management/commands/jembi_submit_babyswitch.py
changes/management/commands/jembi_submit_optouts.py
changes/tasks.py
changes/tests.py
ndoh_hub/utils.py
registrations/tasks.py

For the management commands, some of them rely on the information that was present in the change objects before the change to remove this information.
We want to add this information back, do whatever we need to with it, and then remove it again at the end.

Add personally identifiable information back for change management commands

---

ndoh_hub/settings.py
ndoh_hub/utils.py
registrations/tests.py
setup.py

Currently, we are using the vumi go metrics client. While this works with the seed metrics API, it uses token authentication, while the seed metrics API uses basic authentication. We need to switch to using the seed metrics client, so that we can use authentication for our metrics.

Switch to seed metrics client

---

ndoh_hub/utils_tests.py
registrations/tasks.py
registrations/tests.py

What we want to do, is the day after a mother has registered for the service, they should get an SMS detailing how to connect to the new POPI USSD line.
The way this PR proposes to implement it, is to create a new subscription for the mother, to a special message set that contains just the POPI message/s that we want to send, that detail how to access the new POPI line.

Additional subscription request for POPI messages

---

registrations/tests.py
registrations/views.py

New link for helpdesk outgoing messages on NC helpdesk:
`/ws/rest/v1/nc/helpdesk`
I use the source object linked to the authenticated user to determine which helpdesk the outgoing comes from.
Payload is the same as Momconnect.

New Jembi endpoint for NC helpdesk

---

changes/models.py
changes/tasks.py
changes/tests.py

We want users to be able to switch what channel they're currently receiving messages on. To do this, we need to create a new change type. This change type will be able to switch between the current two messaging options, SMS and WhatsApp

Create change type for switching messaging channel

---

changes/tasks.py
changes/tests.py

The regex for this was incorrect, which resulted in a switch from whatsapp to SMS keeping the user on WhatsApp

Fix regex for switching WhatsApp to SMS
